### ISSUE TITLE
Getting Zone Names

### ISSUE THREAD

**Issue by SiamKreative** [julon/vue-moment-lib#122]
How to get the following within my component (computed)?
http://momentjs.com/timezone/docs/#/data-loading/getting-zone-names/

I tried:
```js
export default {
  name: "TimeZones",
  computed: {
    timezones() {
      return this.$moment.tz.names();
    }
  },
  props: {
    data: Object
  }
};
```

**Comment by julon** [comment]
Hi, for this to work you need to pass a custom moment instance to the lib and install per the documentation the moment timezone plugin to that instance. Sorry for the late reply...
