### ISSUE TITLE
After refreshing the page get this error

### ISSUE THREAD

**Issue by ATUL1995** [julon/vue-moment-lib#89]
it's working perfectly fine but when i'm refreshing the page getting this issues.
"_vm.$moment is not a function"
i'm using the nuxt (vue.js)

**Comment by julon** [comment]
thanks for reporting this, do you have more details on how you declare this lib as a plugin in your nuxt config? You may find some more info there https://medium.com/@codebeast_/why-your-third-party-plugin-dont-work-in-nuxt-and-how-to-fix-it-d1a8caadf422 you may try to disable the ssr mode for this plugin
